const Images = {
  arrowBack: require('../assets/arrowleftwithcircle.png'),
  arrowForward: require('../assets/arrowright.png'),
  arrowforwardwithcircle: require('../assets/arrowforwardwithcircle.png'),
  bglogosplash: require('../assets/bglogosplash.png'),
  bottomsheetheader: require('../assets/bottomsheetheader.png'),
  logosplash: require('../assets/logosplash.png'),
  sliderthumb: require('../assets/sliderthumb.png'),
  logoapple: require('../assets/logoapple.png'),
  logofacebook: require('../assets/logofacebook.png'),
  logogoogle: require('../assets/logogoogle.png'),
  bottombarnearbyselected: require('../assets/bottombarnearbyselected.png'),
  bottombarnearbyunselected: require('../assets/bottombarnearbyunselected.png'),
  bottombarlistselected: require('../assets/bottombarlistselected.png'),
  bottombarlistunselected: require('../assets/bottombarlistunselected.png'),
  bottombarsettingsselected: require('../assets/bottombarsettingsselected.png'),
  bottombarsettingsunselected: require('../assets/bottombarsettingsunselected.png'),
  bottombardrawerselected: require('../assets/bottombardrawerselected.png'),
  bottombardrawerunselected: require('../assets/bottombardrawerunselected.png'),
  bottombarprofileselected: require('../assets/bottombarprofileselected.png'),
  bottombarprofileunselected: require('../assets/bottombarprofileunselected.png'),
  bottombarcenter: require('../assets/bottombarcenter.png'),
  logolistofloc: require('../assets/logolistofloc.png'),
  iconedit: require('../assets/iconedit.png'),
  iconarrowrightbrown: require('../assets/iconarrowrightbrown.png'),
  iconcameracircle: require('../assets/iconcameracircle.png'),
  user: require('../assets/user.png'),
  iconcrosswithcircle: require('../assets/iconcrosswithcircle.png'),
  draweraccount: require('../assets/draweraccount.png'),
  drawerbell: require('../assets/drawerbell.png'),
  draweremailus: require('../assets/draweremailus.png'),
  drawerinfo: require('../assets/drawerinfo.png'),
  drawerlegal: require('../assets/drawerlegal.png'),
  drawerlogout: require('../assets/drawerlogout.png'),
  drawersettings: require('../assets/drawersettings.png'),
  drawersuggestion: require('../assets/drawersuggestion.png'),
  drawertnc: require('../assets/drawertnc.png'),
  marker: require('../assets/marker.png'),
  iconsearch: require('../assets/iconsearch.png'),
  iconfilter: require('../assets/iconfilter.png'),
  eyeOpen: require('../assets/eyeOpen.png'),
};

export default Images;
